### PR TITLE
Allows md.blade.php views to extend blade.php views

### PR DESCRIPTION
**Pull request by lsjroberts**
This fixes #1 by allowing mixing `md.blade.php` and `blade.php` views.

The parser transform has been moved to a `BladeMarkdownCompiler` which extends `BladeCompiler`. This overwrites the `compileSectionStart()` method to allow the content within a section to be transformed from markdown before converted from blade to php.

This allows:

```
// foo.md.blade.php
@extends('layout')

@section('content')
# FooBar
@stop
```

```
// layout.blade.php
<html>
    <body>
        @yield('content')
    </body>
</html>
```

### CODE REVIEW

**Comment by Weeblewonder** [comment]
+1 for getting this in. This is the answer to my prayers except for this one stumbling block.

**Comment by lsjroberts** [comment]
Will need to revert the `composer.json` changes before merging.

**Comment by gms8994** [comment]
Is this going to get merged? As it is, I'm unable to use this without being able to extend a layout.

**Comment by lsjroberts** [comment]
I'll do some testing at the weekend to check it still works and check for any improvements.

**Comment by lsjroberts** [comment]
This actually requires a fork I made of `dflydev/markdown` which I deleted at some point forgetting I needed it for this.

I'd suggest actually switching the parser to use https://github.com/michelf/php-markdown/ as the markdown parser as it seems more supported.

**Comment by Kindari** [comment]
Hey guys, somehow I never realised these pull requests / issues were even created, I only thought I myself was using this. I'll spend a little time reviewing this, but I don't see any reason why not to merge it.

**Comment by lsjroberts** [comment]
@Kindari The code may not actually work due to the fork of `dflydev/markdown` so I'd suggest checking it out first.

**Pull request closed without merging**
